// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Procurement.Infrastructure.Persistence;

#nullable disable

namespace Wms.Procurement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    partial class ProcurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.ApprovalInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("CurrentStep")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("current_step");

                    b.Property<long>("DocId")
                        .HasColumnType("bigint")
                        .HasColumnName("doc_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("doc_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('PENDING','APPROVED','REJECTED','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_proc_approval_instance");

                    b.HasIndex("TenantId", "DocType", "DocId")
                        .HasDatabaseName("ix_ai");

                    b.ToTable("proc_approval_instance", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.ApprovalRule", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("ApproverRoleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("approver_role_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxAmountBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("max_amount_base");

                    b.Property<decimal>("MinAmountBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("min_amount_base");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("enum('FOOD','NON_FOOD','ANY')")
                        .HasColumnName("product_type");

                    b.Property<byte>("StepNo")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("step_no");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_proc_approval_rule");

                    b.HasIndex("TenantId", "DocType", "ProductType", "MinAmountBase")
                        .HasDatabaseName("ix_rule");

                    b.ToTable("proc_approval_rule", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<uint?>("ApproverUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("approver_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("enum('PENDING','APPROVED','REJECTED')")
                        .HasColumnName("decision");

                    b.Property<uint?>("DelegatedFromUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("delegated_from_user_id");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("instance_id");

                    b.Property<byte>("StepNo")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("step_no");

                    b.HasKey("Id")
                        .HasName("pk_proc_approval_step");

                    b.HasIndex("InstanceId", "StepNo")
                        .HasDatabaseName("ix_as");

                    b.ToTable("proc_approval_step", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<uint>("DeliveryLocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("delivery_location_id");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<DateOnly?>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("fx_rate");

                    b.Property<string>("Incoterms")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("incoterms");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','SENT_TO_SUPPLIER','PARTIALLY_RECEIVED','FULLY_RECEIVED','CLOSED','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("subtotal");

                    b.Property<uint>("SupplierId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TotalAmountBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_amount_base");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("vat_amount");

                    b.HasKey("Id")
                        .HasName("pk_proc_purchase_order");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_po");

                    b.ToTable("proc_purchase_order", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("line_total");

                    b.Property<long>("PoId")
                        .HasColumnType("bigint")
                        .HasColumnName("po_id");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<decimal>("ReceivedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("received_qty");

                    b.Property<long?>("RequisitionLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("requisition_line_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id")
                        .HasName("pk_proc_purchase_order_line");

                    b.HasIndex("PoId")
                        .HasDatabaseName("ix_proc_purchase_order_line_po_id");

                    b.HasIndex("TenantId", "PoId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_pol");

                    b.ToTable("proc_purchase_order_line", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.Requisition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("enum('LOW','NORMAL','HIGH','URGENT')")
                        .HasColumnName("priority");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("enum('FOOD','NON_FOOD')")
                        .HasColumnName("product_type");

                    b.Property<uint>("RequesterLocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("requester_location_id");

                    b.Property<DateOnly?>("RequiredDate")
                        .HasColumnType("date")
                        .HasColumnName("required_date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','SUBMITTED','IN_PROCUREMENT','CONVERTED_TO_PO','REJECTED','CANCELLED','CLOSED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_proc_requisition");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_pr");

                    b.ToTable("proc_requisition", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.RequisitionLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConvertedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("converted_qty");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<long>("RequisitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("requisition_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_proc_requisition_line");

                    b.HasIndex("RequisitionId")
                        .HasDatabaseName("ix_proc_requisition_line_requisition_id");

                    b.HasIndex("TenantId", "RequisitionId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_prl");

                    b.ToTable("proc_requisition_line", (string)null);
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("Wms.Procurement.Domain.Entities.ApprovalInstance", null)
                        .WithMany("Steps")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proc_approval_step_proc_approval_instance_instance_id");
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("Wms.Procurement.Domain.Entities.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proc_purchase_order_line_proc_purchase_order_po_id");
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.RequisitionLine", b =>
                {
                    b.HasOne("Wms.Procurement.Domain.Entities.Requisition", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proc_requisition_line_proc_requisition_requisition_id");
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.ApprovalInstance", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Procurement.Domain.Entities.Requisition", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
