// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Reporting.Infrastructure.Persistence;

#nullable disable

namespace Wms.Reporting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Reporting.Domain.Entities.ExportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("file_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("enum('XLSX','CSV','PDF')")
                        .HasColumnName("format");

                    b.Property<Guid>("IdempotencyKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IncludeCost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("include_cost");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("locale");

                    b.Property<string>("LocationScopeJson")
                        .HasColumnType("json")
                        .HasColumnName("location_scope_json");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters_json");

                    b.Property<byte?>("ProgressPct")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("progress_pct");

                    b.Property<string>("ReportCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("report_code");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("requested_at");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("requested_by");

                    b.Property<long?>("RowCount")
                        .HasColumnType("bigint")
                        .HasColumnName("row_count");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("storage_key");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rpt_export_job");

                    b.HasIndex("TenantId", "RequestedBy", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_rpt_export_idem");

                    b.HasIndex("TenantId", "RequestedBy", "RequestedAt")
                        .HasDatabaseName("ix_rpt_export_user");

                    b.HasIndex("TenantId", "Status", "RequestedAt")
                        .HasDatabaseName("ix_rpt_export_status");

                    b.ToTable("rpt_export_job", (string)null);
                });

            modelBuilder.Entity("Wms.Reporting.Domain.Entities.ReportDefinition", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("code");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("columns_json");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxSyncRows")
                        .HasColumnType("int")
                        .HasColumnName("max_sync_rows");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters_json");

                    b.Property<bool>("RequiresCostPermission")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_cost_permission");

                    b.Property<ushort>("SortOrder")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("sort_order");

                    b.Property<string>("SupportedFormats")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("supported_formats");

                    b.Property<bool>("SupportsExcelExport")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("supports_excel_export");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TorRef")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tor_ref");

                    b.HasKey("Id")
                        .HasName("pk_rpt_report_definition");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_rpt_report");

                    b.HasIndex("TenantId", "Category", "SortOrder")
                        .HasDatabaseName("ix_rpt_report_cat");

                    b.ToTable("rpt_report_definition", (string)null);
                });

            modelBuilder.Entity("Wms.Reporting.Domain.Entities.StockSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvgUnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("avg_unit_cost");

                    b.Property<DateTimeOffset>("BuiltAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("built_at");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QtyOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty_on_hand");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_rpt_stock_snapshot");

                    b.HasIndex("TenantId", "SnapshotDate", "LocationId")
                        .HasDatabaseName("ix_rpt_snapshot_loc");

                    b.HasIndex("TenantId", "SnapshotDate", "ProductId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("uq_rpt_snapshot");

                    b.ToTable("rpt_stock_snapshot", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
