// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Identity.Infrastructure.Persistence;

#nullable disable

namespace Wms.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.Delegation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<uint>("FromUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("reason");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("ToUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("to_user_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_iam_delegation");

                    b.HasIndex("TenantId", "FromUserId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_deleg");

                    b.ToTable("iam_delegation", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("code");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("module");

                    b.HasKey("Id")
                        .HasName("pk_iam_permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_perm_code");

                    b.ToTable("iam_permission", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("code");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_iam_role");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_role_code");

                    b.ToTable("iam_role", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("role_id");

                    b.Property<ushort>("PermissionId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_iam_role_permission");

                    b.ToTable("iam_role_permission", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.Tenant", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("default_currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_iam_tenant");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_tenant_code");

                    b.ToTable("iam_tenant", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_iam_user");

                    b.HasIndex("TenantId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_external");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("uq_user_username");

                    b.ToTable("iam_user", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.UserLocation", b =>
                {
                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.HasKey("UserId", "LocationId")
                        .HasName("pk_iam_user_location");

                    b.ToTable("iam_user_location", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_iam_user_role");

                    b.ToTable("iam_user_role", (string)null);
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.UserLocation", b =>
                {
                    b.HasOne("Wms.Identity.Domain.Entities.User", null)
                        .WithMany("Locations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_user_location_iam_user_user_id");
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Wms.Identity.Domain.Entities.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_user_role_iam_user_user_id");
                });

            modelBuilder.Entity("Wms.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
