<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Identity persistence, contract implementations and jobs.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Wms.Identity.Application/Wms.Identity.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Wms.Common.Infrastructure/Wms.Common.Infrastructure.csproj" />
  </ItemGroup>
</Project>
