// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.MasterData.Infrastructure.Persistence;

#nullable disable

namespace Wms.MasterData.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MasterDataDbContext))]
    [Migration("20260921032351_20260921_MasterData_Initial")]
    partial class _20260921_MasterData_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.CurrencyRate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<decimal>("RateToBase")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("rate_to_base");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_master_currency_rate");

                    b.HasIndex("TenantId", "Currency", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("uq_rate");

                    b.ToTable("master_currency_rate", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.Location", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("AllowsFood")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allows_food");

                    b.Property<bool>("AllowsNonFood")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allows_non_food");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_virtual");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("enum('CENTRAL_WAREHOUSE','SUB_LOCATION','SHELF','RESTAURANT','IN_TRANSIT','V_SUPPLIER','V_WASTE','V_SAMPLE','V_ADJUSTMENT')")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<uint?>("ParentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("parent_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_master_location");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_loc_code");

                    b.HasIndex("TenantId", "ParentId")
                        .HasDatabaseName("ix_loc_parent");

                    b.ToTable("master_location", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.NumberSequence", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("doc_type");

                    b.Property<uint>("LastNumber")
                        .HasColumnType("int unsigned")
                        .HasColumnName("last_number");

                    b.Property<byte>("Padding")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("padding");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("period");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("prefix");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_master_number_sequence");

                    b.HasIndex("TenantId", "DocType", "Period")
                        .IsUnique()
                        .HasDatabaseName("uq_seq");

                    b.ToTable("master_number_sequence", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.Product", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("barcode");

                    b.Property<ushort>("BaseUomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("base_uom_id");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("brand");

                    b.Property<uint>("CategoryId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<uint?>("DefaultSupplierId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("default_supplier_id");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("IssueStrategy")
                        .IsRequired()
                        .HasColumnType("enum('FEFO','FIFO')")
                        .HasColumnName("issue_strategy");

                    b.Property<decimal?>("MaxStock")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("max_stock");

                    b.Property<decimal?>("MinStock")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<string>("NameSortKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name_sort_key");

                    b.Property<decimal?>("ReorderPoint")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("reorder_point");

                    b.Property<bool>("RequiresBatch")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_batch");

                    b.Property<bool>("RequiresExpiry")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_expiry");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<ushort?>("ShelfLifeDays")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("shelf_life_days");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("sku");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id")
                        .HasName("pk_master_product");

                    b.HasIndex("TenantId", "CategoryId")
                        .HasDatabaseName("ix_product_cat");

                    b.HasIndex("TenantId", "NameSortKey")
                        .HasDatabaseName("ix_product_name");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_product_sku");

                    b.ToTable("master_product", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<uint?>("ParentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("path");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("enum('FOOD','NON_FOOD')")
                        .HasColumnName("product_type");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_master_product_category");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_cat");

                    b.ToTable("master_product_category", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.ProductUom", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("FactorToBase")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("factor_to_base");

                    b.Property<bool>("IsIssueDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_issue_default");

                    b.Property<bool>("IsPurchaseDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_purchase_default");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_master_product_uom");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_master_product_uom_product_id");

                    b.HasIndex("TenantId", "ProductId", "UomId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("uq_puom");

                    b.ToTable("master_product_uom", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.ReasonCode", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("ReasonGroup")
                        .IsRequired()
                        .HasColumnType("enum('WASTE','ADJUSTMENT','RETURN','SAMPLE','TRANSFER')")
                        .HasColumnName("reason_group");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_approval");

                    b.Property<bool>("RequiresPhoto")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_photo");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_master_reason_code");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_reason");

                    b.ToTable("master_reason_code", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.Supplier", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("BankDetails")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("bank_details");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DeliveryTerms")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("delivery_terms");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Incoterms")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("incoterms");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsApprovedFoodSupplier")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_approved_food_supplier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("payment_terms");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("phone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_master_supplier");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_supplier_code");

                    b.ToTable("master_supplier", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.SupplierCertificate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<long?>("AttachmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("attachment_id");

                    b.Property<string>("CertNumber")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("cert_number");

                    b.Property<string>("CertType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("cert_type");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<uint>("SupplierId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_master_supplier_certificate");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_master_supplier_certificate_supplier_id");

                    b.HasIndex("TenantId", "ExpiryDate")
                        .HasDatabaseName("ix_cert_exp");

                    b.ToTable("master_supplier_certificate", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.Uom", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("code");

                    b.Property<byte>("Decimals")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("decimals");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UomClass")
                        .IsRequired()
                        .HasColumnType("enum('MASS','VOLUME','COUNT')")
                        .HasColumnName("uom_class");

                    b.HasKey("Id")
                        .HasName("pk_master_uom");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_uom");

                    b.ToTable("master_uom", (string)null);
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.ProductUom", b =>
                {
                    b.HasOne("Wms.MasterData.Domain.Entities.Product", null)
                        .WithMany("Uoms")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_product_uom_master_product_product_id");
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.SupplierCertificate", b =>
                {
                    b.HasOne("Wms.MasterData.Domain.Entities.Supplier", null)
                        .WithMany("Certificates")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_supplier_certificate_suppliers_supplier_id");
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.Product", b =>
                {
                    b.Navigation("Uoms");
                });

            modelBuilder.Entity("Wms.MasterData.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
