// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Notification.Infrastructure.Persistence;

#nullable disable

namespace Wms.Notification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260921032403_20260921_Notification_Initial")]
    partial class _20260921_Notification_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Notification.Domain.Entities.NotificationMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("read_at");

                    b.Property<string>("RecipientRole")
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("recipient_role");

                    b.Property<uint?>("RecipientUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("enum('INFO','WARNING','CRITICAL')")
                        .HasColumnName("severity");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notif_message");

                    b.HasIndex("TenantId", "RecipientUserId", "ReadAt")
                        .HasDatabaseName("ix_notif_inbox");

                    b.HasIndex("TenantId", "EventId", "RecipientUserId", "RecipientRole")
                        .IsUnique()
                        .HasDatabaseName("uq_notif_event");

                    b.ToTable("notif_message", (string)null);
                });

            modelBuilder.Entity("Wms.Notification.Domain.Entities.NotificationRule", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("channel");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("recipient_role");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("enum('INFO','WARNING','CRITICAL')")
                        .HasColumnName("severity");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_notif_rule");

                    b.HasIndex("TenantId", "EventType", "RecipientRole", "Channel")
                        .IsUnique()
                        .HasDatabaseName("uq_notif_rule");

                    b.ToTable("notif_rule", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
