// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Integration.Infrastructure.Persistence;

#nullable disable

namespace Wms.Integration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260921032409_20260921_Integration_Initial")]
    partial class _20260921_Integration_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Integration.Domain.Entities.IntegrationEndpoint", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("AuthRef")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("auth_ref");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("base_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("system_code");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_intg_endpoint");

                    b.HasIndex("TenantId", "SystemCode")
                        .IsUnique()
                        .HasDatabaseName("uq_intg_endpoint");

                    b.ToTable("intg_endpoint", (string)null);
                });

            modelBuilder.Entity("Wms.Integration.Domain.Entities.OutboundMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('PENDING','SENT','FAILED','SKIPPED')")
                        .HasColumnName("status");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("system_code");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_intg_outbound_message");

                    b.HasIndex("TenantId", "Status", "Id")
                        .HasDatabaseName("ix_intg_pending");

                    b.HasIndex("TenantId", "SystemCode", "EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_intg_event");

                    b.ToTable("intg_outbound_message", (string)null);
                });

            modelBuilder.Entity("Wms.Integration.Domain.Entities.SyncCursor", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("LastCursor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("last_cursor");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resource");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("system_code");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_intg_sync_cursor");

                    b.HasIndex("TenantId", "SystemCode", "Resource")
                        .IsUnique()
                        .HasDatabaseName("uq_intg_cursor");

                    b.ToTable("intg_sync_cursor", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
