// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Inventory.Infrastructure.Persistence;

#nullable disable

namespace Wms.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260921140527_20260921_Inventory_WarehouseDocuments")]
    partial class _20260921_Inventory_WarehouseDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("batch_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("received_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('ACTIVE','BLOCKED','EXPIRED','QUARANTINE')")
                        .HasColumnName("status");

                    b.Property<uint?>("SupplierId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_batch");

                    b.HasIndex("TenantId", "ProductId", "BatchNo", "ExpiryDate")
                        .IsUnique()
                        .HasDatabaseName("uq_batch");

                    b.HasIndex("TenantId", "ProductId", "Status", "ExpiryDate", "ReceivedAt")
                        .HasDatabaseName("ix_batch_fefo");

                    b.ToTable("inv_batch", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<long?>("MovementGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_group_id");

                    b.Property<string>("PackagingNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("packaging_note");

                    b.Property<long?>("PoId")
                        .HasColumnType("bigint")
                        .HasColumnName("po_id");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasColumnType("enum('ACCEPTED','PARTIALLY_ACCEPTED','REJECTED')")
                        .HasColumnName("quality_status");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','POSTED','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<uint>("SupplierId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<decimal?>("TemperatureC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("temperature_c");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_goods_receipt");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_gr");

                    b.ToTable("inv_goods_receipt", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("batch_no");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<decimal?>("OrderedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ordered_qty");

                    b.Property<long?>("PoLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("po_line_id");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_id");

                    b.Property<decimal>("ReceivedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("received_qty");

                    b.Property<decimal>("RejectedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("rejected_qty");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.Property<string>("VarianceNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("variance_note");

                    b.HasKey("Id")
                        .HasName("pk_inv_goods_receipt_line");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_inv_goods_receipt_line_receipt_id");

                    b.HasIndex("TenantId", "ReceiptId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_grl");

                    b.ToTable("inv_goods_receipt_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.InventorySetting", b =>
                {
                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("setting_key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("setting_value");

                    b.HasKey("TenantId", "Key")
                        .HasName("pk_inv_setting");

                    b.ToTable("inv_setting", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<long?>("DispatchGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispatch_group_id");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("dispatched_at");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<uint>("FromLocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("from_location_id");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("enum('BRANCH_ISSUE','WH_TRANSFER','BRANCH_TRANSFER')")
                        .HasColumnName("issue_type");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<long?>("ReceiptGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_group_id");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("received_at");

                    b.Property<uint?>("ReceivedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("received_by");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','DISPATCHED','RECEIVED','DISCREPANCY','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("ToLocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("to_location_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_issue");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_issue");

                    b.HasIndex("TenantId", "Status", "ToLocationId")
                        .HasDatabaseName("ix_issue_status");

                    b.ToTable("inv_issue", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.IssueLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<string>("BatchOverrideNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("batch_override_note");

                    b.Property<ushort?>("BatchOverrideReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("batch_override_reason_code_id");

                    b.Property<string>("DiscrepancyNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("discrepancy_note");

                    b.Property<decimal?>("DiscrepancyQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("discrepancy_qty");

                    b.Property<ushort?>("DiscrepancyReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("discrepancy_reason_code_id");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_base");

                    b.Property<decimal?>("ReceivedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("received_qty");

                    b.Property<long?>("RequestLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_line_id");

                    b.Property<long?>("SuggestedBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("suggested_batch_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_inv_issue_line");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_inv_issue_line_issue_id");

                    b.HasIndex("TenantId", "IssueId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_isl");

                    b.ToTable("inv_issue_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Movement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("BaseUomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("base_uom_id");

                    b.Property<long?>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("conversion_rate");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("EnteredQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("entered_qty");

                    b.Property<ushort>("EnteredUomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("entered_uom_id");

                    b.Property<decimal?>("FxRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("fx_rate");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("posted_at");

                    b.Property<uint>("PostedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("posted_by");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty_base");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_inv_movement");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_inv_movement_group_id");

                    b.HasIndex("TenantId", "PostedAt")
                        .HasDatabaseName("ix_mv_posted");

                    b.HasIndex("TenantId", "GroupId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_mv_line");

                    b.HasIndex("TenantId", "ProductId", "LocationId", "BatchId", "Id")
                        .HasDatabaseName("ix_mv_balance");

                    b.ToTable("inv_movement", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.MovementGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("enum('RECEIPT','ISSUE','TRANSFER','COUNT_ADJUST','WASTE','SAMPLE','RETURN','OPENING','REVERSAL','CONSUMPTION')")
                        .HasColumnName("doc_type");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("posted_at");

                    b.Property<uint>("PostedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("posted_by");

                    b.Property<ushort?>("ReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("reason_code_id");

                    b.Property<long?>("ReversesGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("reverses_group_id");

                    b.Property<long?>("SourceDocId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_doc_id");

                    b.Property<string>("SourceDocType")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("source_doc_type");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inv_movement_group");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_mg_idem");

                    b.HasIndex("TenantId", "DocType", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_mg_doc");

                    b.HasIndex("TenantId", "SourceDocType", "SourceDocId")
                        .HasDatabaseName("ix_mg_src");

                    b.ToTable("inv_movement_group", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.ReturnToVendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ClaimAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("claim_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<long?>("MovementGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_group_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("OutcomeNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("outcome_note");

                    b.Property<ushort>("ReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("reason_code_id");

                    b.Property<long?>("ReceiptId")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','SENT','ACCEPTED','REJECTED','CLOSED')")
                        .HasColumnName("status");

                    b.Property<uint>("SupplierId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_return_to_vendor");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_rtv");

                    b.ToTable("inv_return_to_vendor", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.ReturnToVendorLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_base");

                    b.Property<long>("ReturnId")
                        .HasColumnType("bigint")
                        .HasColumnName("return_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_inv_return_to_vendor_line");

                    b.HasIndex("ReturnId")
                        .HasDatabaseName("ix_inv_return_to_vendor_line_return_id");

                    b.HasIndex("TenantId", "ReturnId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_rtvl");

                    b.ToTable("inv_return_to_vendor_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("authority");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<long?>("MovementGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_group_id");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("purpose");

                    b.Property<ushort?>("ReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("reason_code_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_sample");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_sample");

                    b.ToTable("inv_sample", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.SampleLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_base");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_inv_sample_line");

                    b.HasIndex("SampleId")
                        .HasDatabaseName("ix_inv_sample_line_sample_id");

                    b.HasIndex("TenantId", "SampleId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_sml");

                    b.ToTable("inv_sample_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockBalance", b =>
                {
                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<long>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("batch_id");

                    b.Property<decimal>("AvgUnitCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_unit_cost");

                    b.Property<long?>("LastMovementId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_movement_id");

                    b.Property<decimal>("QtyOnHand")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_on_hand");

                    b.Property<decimal>("QtyReserved")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_reserved");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "ProductId", "LocationId", "BatchId")
                        .HasName("pk_inv_balance");

                    b.HasIndex("TenantId", "LocationId", "ProductId")
                        .HasDatabaseName("ix_bal_loc");

                    b.ToTable("inv_balance", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockCount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdjustGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("adjust_group_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("approved_at");

                    b.Property<uint?>("ApprovedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("approved_by");

                    b.Property<string>("CountType")
                        .IsRequired()
                        .HasColumnType("enum('FULL','CYCLE','SPOT')")
                        .HasColumnName("count_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("frozen_at");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_approval");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("ScopeCategoryIds")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("scope_category_ids");

                    b.Property<string>("ScopeProductIds")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("scope_product_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','FROZEN','COUNTING','REVIEW','APPROVED','POSTED','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_count");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_count");

                    b.HasIndex("TenantId", "LocationId", "Status")
                        .HasDatabaseName("ix_count_loc");

                    b.ToTable("inv_count", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockCountLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvgUnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_unit_cost");

                    b.Property<long?>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("BookQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("book_qty");

                    b.Property<long>("CountId")
                        .HasColumnType("bigint")
                        .HasColumnName("count_id");

                    b.Property<DateTimeOffset?>("CountedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("counted_at");

                    b.Property<uint?>("CountedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("counted_by");

                    b.Property<decimal?>("CountedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("counted_qty");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<ushort?>("ReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("reason_code_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("VariancePct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("variance_pct");

                    b.Property<decimal?>("VarianceQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("variance_qty");

                    b.HasKey("Id")
                        .HasName("pk_inv_count_line");

                    b.HasIndex("CountId")
                        .HasDatabaseName("ix_inv_count_line_count_id");

                    b.HasIndex("TenantId", "CountId", "ProductId")
                        .HasDatabaseName("ix_cl");

                    b.HasIndex("TenantId", "CountId", "ProductId", "BatchId")
                        .IsUnique()
                        .HasDatabaseName("uq_cl_line");

                    b.ToTable("inv_count_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<uint>("FromLocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("from_location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("RequiredDate")
                        .HasColumnType("date")
                        .HasColumnName("required_date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','SUBMITTED','PICKING','PARTIALLY_ISSUED','ISSUED','CANCELLED','CLOSED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("ToLocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("to_location_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_stock_request");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_sr");

                    b.HasIndex("TenantId", "ToLocationId", "Status")
                        .HasDatabaseName("ix_sr_to");

                    b.ToTable("inv_stock_request", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockRequestLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("IssuedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("issued_qty");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_inv_stock_request_line");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_inv_stock_request_line_request_id");

                    b.HasIndex("TenantId", "RequestId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_srl");

                    b.ToTable("inv_stock_request_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Waste", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApprovalComment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("approval_comment");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("approved_at");

                    b.Property<uint?>("ApprovedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<long?>("MovementGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_group_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<ushort>("ReasonCodeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("reason_code_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','PENDING_APPROVAL','APPROVED','POSTED','REJECTED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inv_waste");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_waste");

                    b.HasIndex("TenantId", "LocationId", "Status")
                        .HasDatabaseName("ix_waste_loc");

                    b.ToTable("inv_waste", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.WasteLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_base");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.Property<long>("WasteId")
                        .HasColumnType("bigint")
                        .HasColumnName("waste_id");

                    b.HasKey("Id")
                        .HasName("pk_inv_waste_line");

                    b.HasIndex("WasteId")
                        .HasDatabaseName("ix_inv_waste_line_waste_id");

                    b.HasIndex("TenantId", "WasteId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_wl");

                    b.ToTable("inv_waste_line", (string)null);
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.GoodsReceipt", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_goods_receipt_line_inv_goods_receipt_receipt_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.IssueLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.Issue", null)
                        .WithMany("Lines")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_issue_line_inv_issue_issue_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Movement", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.MovementGroup", null)
                        .WithMany("Lines")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inv_movement_inv_movement_group_group_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.ReturnToVendorLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.ReturnToVendor", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_return_to_vendor_line_inv_return_to_vendor_return_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.SampleLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.Sample", null)
                        .WithMany("Lines")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_sample_line_inv_sample_sample_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockCountLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.StockCount", null)
                        .WithMany("Lines")
                        .HasForeignKey("CountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_count_line_inv_count_count_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockRequestLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.StockRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_stock_request_line_inv_stock_request_request_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.WasteLine", b =>
                {
                    b.HasOne("Wms.Inventory.Domain.Entities.Waste", null)
                        .WithMany("Lines")
                        .HasForeignKey("WasteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_waste_line_inv_waste_waste_id");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.MovementGroup", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.ReturnToVendor", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Sample", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockCount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.StockRequest", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Inventory.Domain.Entities.Waste", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
