// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Consumption.Infrastructure.Persistence;

#nullable disable

namespace Wms.Consumption.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsumptionDbContext))]
    [Migration("20260921044112_20260921_Consumption_Initial")]
    partial class _20260921_Consumption_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Common.Infrastructure.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','POST','REVERSE','EXPORT')")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_common_audit_log");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit");

                    b.ToTable("common_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("AttemptCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("processed_at");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_common_outbox");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("common_outbox", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.ConsumptionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset?>("CalculatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("calculated_at");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("doc_no");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("failure_reason");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_id");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<long?>("MovementGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_group_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("posted_at");

                    b.Property<uint?>("PostedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("posted_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<ushort>("ShortfallCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("shortfall_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','CALCULATED','POSTED','FAILED','REVERSED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<ushort>("UnmappedCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("unmapped_count");

                    b.HasKey("Id")
                        .HasName("pk_cons_run");

                    b.HasIndex("TenantId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("uq_run_doc");

                    b.HasIndex("TenantId", "LocationId", "BusinessDate")
                        .IsUnique()
                        .HasDatabaseName("uq_run_day");

                    b.HasIndex("TenantId", "Status", "BusinessDate")
                        .HasDatabaseName("ix_run_status");

                    b.ToTable("cons_run", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.ConsumptionRunLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ushort>("BaseUomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("base_uom_id");

                    b.Property<decimal>("PostedQtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("posted_qty_base");

                    b.Property<uint>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<decimal>("ShortfallQtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("shortfall_qty_base");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TheoreticalQtyBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("theoretical_qty_base");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_cons_run_line");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_cons_run_line_run_id");

                    b.HasIndex("TenantId", "RunId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_rl");

                    b.ToTable("cons_run_line", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.MenuItem", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSubRecipe")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sub_recipe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<string>("NameSortKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name_sort_key");

                    b.Property<string>("PosCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pos_code");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint?>("UpdatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cons_menu_item");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_menu_code");

                    b.HasIndex("TenantId", "NameSortKey")
                        .HasDatabaseName("ix_menu_name");

                    b.HasIndex("TenantId", "PosCode")
                        .IsUnique()
                        .HasDatabaseName("uq_menu_pos");

                    b.ToTable("cons_menu_item", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.Recipe", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<uint>("CreatedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by");

                    b.Property<uint>("MenuItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','ACTIVE','ARCHIVED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<ushort>("VersionNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("version_no");

                    b.Property<decimal>("YieldPortions")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1.0000m)
                        .HasColumnName("yield_portions");

                    b.HasKey("Id")
                        .HasName("pk_cons_recipe");

                    b.HasIndex("TenantId", "MenuItemId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("uq_recipe_ver");

                    b.HasIndex("TenantId", "MenuItemId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_recipe_eff");

                    b.ToTable("cons_recipe", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.RecipeLine", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("AttachRatePct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasDefaultValue(100.0000m)
                        .HasColumnName("attach_rate_pct");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("enum('FOOD_PRODUCT','SUB_RECIPE')")
                        .HasColumnName("component_type");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_optional");

                    b.Property<ushort>("LineNo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("line_no");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<uint?>("ProductId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QtyPerPortion")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty_per_portion");

                    b.Property<uint>("RecipeId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("recipe_id");

                    b.Property<uint?>("SubMenuItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("sub_menu_item_id");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.Property<ushort>("UomId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("uom_id");

                    b.Property<decimal>("YieldPct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasDefaultValue(100.0000m)
                        .HasColumnName("yield_pct");

                    b.HasKey("Id")
                        .HasName("pk_cons_recipe_line");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_cons_recipe_line_recipe_id");

                    b.HasIndex("TenantId", "RecipeId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_rline");

                    b.ToTable("cons_recipe_line", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.SalesImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("external_ref");

                    b.Property<decimal?>("GrossAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("gross_amount");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("imported_at");

                    b.Property<uint>("ImportedBy")
                        .HasColumnType("int unsigned")
                        .HasColumnName("imported_by");

                    b.Property<ushort>("LineCount")
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("line_count");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("row_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("enum('POS','CSV','MANUAL')")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('DRAFT','SUBMITTED','CONSUMED','CANCELLED')")
                        .HasColumnName("status");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_cons_sales_import");

                    b.HasIndex("TenantId", "LocationId", "BusinessDate")
                        .IsUnique()
                        .HasDatabaseName("uq_sales_day");

                    b.HasIndex("TenantId", "Status", "BusinessDate")
                        .HasDatabaseName("ix_sales_status");

                    b.ToTable("cons_sales_import", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.SalesLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("GrossAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("gross_amount");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_id");

                    b.Property<uint?>("MenuItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("menu_item_id");

                    b.Property<decimal>("QtySold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty_sold");

                    b.Property<string>("RawPosCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("raw_pos_code");

                    b.Property<uint>("TenantId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_cons_sales_line");

                    b.HasIndex("ImportId")
                        .HasDatabaseName("ix_cons_sales_line_import_id");

                    b.HasIndex("TenantId", "ImportId", "MenuItemId", "RawPosCode")
                        .IsUnique()
                        .HasDatabaseName("uq_sline");

                    b.ToTable("cons_sales_line", (string)null);
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.ConsumptionRunLine", b =>
                {
                    b.HasOne("Wms.Consumption.Domain.Entities.ConsumptionRun", null)
                        .WithMany("Lines")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cons_run_line_cons_run_run_id");
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.RecipeLine", b =>
                {
                    b.HasOne("Wms.Consumption.Domain.Entities.Recipe", null)
                        .WithMany("Lines")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cons_recipe_line_cons_recipe_recipe_id");
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.SalesLine", b =>
                {
                    b.HasOne("Wms.Consumption.Domain.Entities.SalesImport", null)
                        .WithMany("Lines")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cons_sales_line_cons_sales_import_import_id");
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.ConsumptionRun", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Consumption.Domain.Entities.SalesImport", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
