#!/usr/bin/env bash
# load-db-switch.sh — points the running API containers at a different database and back.
#
#   scripts/load-db-switch.sh wms_load     # before the load test
#   scripts/load-db-switch.sh wms          # after it
#
# Only the connection string changes: the images, the migrations and the realm stay as they are, so
# nothing about the code under measurement differs between the two runs. The gateway is not touched —
# it proxies by hostname and holds no connection string.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${1:-}"
[ -z "$TARGET" ] && { sed -n '2,12p' "$0"; exit 2; }

SERVICES="wms-identity wms-masterdata wms-inventory wms-procurement wms-reporting wms-worker"
OVERRIDE="$ROOT_DIR/deploy/docker-compose.loaddb.yml"

if [ "$TARGET" = "wms" ]; then
  echo "restoring the working database"
  rm -f "$OVERRIDE"
else
  echo "pointing the API at $TARGET"
  {
    echo "# Generated by scripts/load-db-switch.sh — delete it to go back to the working database."
    echo "# Only the connection string differs, so the code under measurement is identical."
    echo "services:"
    for svc in $SERVICES; do
      echo "  $svc:"
      echo "    environment:"
      echo "      ConnectionStrings__Wms: Server=mysql;Port=3306;Database=$TARGET;User=wms_app;Password=\${MYSQL_APP_PASSWORD:-wms_app};"
    done
  } > "$OVERRIDE"
fi

cd "$ROOT_DIR/deploy"
FILES=(-f docker-compose.yml)
[ -f "$OVERRIDE" ] && FILES+=(-f docker-compose.loaddb.yml)

docker compose "${FILES[@]}" --profile infra --profile app up -d --no-deps $SERVICES >/dev/null 2>&1

echo "waiting for readiness"
for port in 5081 5082 5083 5084 5085 5086; do
  for _ in $(seq 1 40); do
    if curl -sf -m 3 "http://localhost:$port/health/ready" >/dev/null 2>&1; then break; fi
    sleep 3
  done
done

echo "now serving: $(curl -s -m 5 http://localhost:5083/health/ready >/dev/null 2>&1 && echo "$TARGET (inventory ready)" || echo 'NOT READY')"
