<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Notification use cases (commands, queries, handlers).</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Wms.Notification.Domain/Wms.Notification.Domain.csproj" />
    <ProjectReference Include="../Wms.Notification.Contracts/Wms.Notification.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Wms.Common.Application/Wms.Common.Application.csproj" />
  </ItemGroup>
</Project>
